// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvw6V-WXp03tOJ0TUdkLm6eo4v549R-zU',
    appId: '1:539505907325:android:617b1669f1382d7f0b8314',
    messagingSenderId: '539505907325',
    projectId: 'farm-pro-2a193',
    databaseURL: 'https://farm-pro-2a193-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farm-pro-2a193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFGP13UvzXUV1N_1Em2zfXj0WPzyDyOtQ',
    appId: '1:539505907325:ios:a55de118a4238cd50b8314',
    messagingSenderId: '539505907325',
    projectId: 'farm-pro-2a193',
    databaseURL: 'https://farm-pro-2a193-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farm-pro-2a193.appspot.com',
    androidClientId: '539505907325-aq6s0lkcbu40kq0crvpcc77botl6jh9f.apps.googleusercontent.com',
    iosClientId: '539505907325-ts3560g96m00dtmdovbi1o3iel0shb4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmPro',
  );

}